language: android

sudo:
  - false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra-google-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x deploy_bintray.sh

script:
  - ./gradlew test --stacktrace

after_success:
#  - ./gradlew jacocoTestReport
#  - bash <(curl -s https://codecov.io/bash)
  - ./deploy_bintray.sh

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
